variables:
  # older versions of git have issues fetching.
  GIT_STRATEGY: clone

tag-image:
  only:
    - tags
  script: |
    IMG="docker-registry.osc.edu/gateways/phylogatr"
    TAG="$IMG:$CI_COMMIT_TAG"
    LATEST="$IMG:latest"

    docker build -t $TAG .
    docker tag $TAG $LATEST

    docker push $TAG
    docker push $LATEST
