#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=28
#SBATCH -t 40:00:00
#SBATCH --job-name="align_phylogatr"

set -xe

export WORKDIR=${WORKDIR:-/fs/project/PAS1604/pipeline/dev}

# if you want to set a timeout for alignments, this is a way to ensure the majority of alignments
# will get done in a timely manner, and then you can resubmit a job without the timelimit
#
#    export TIMEOUT=10m
#
# or
#
#    export TIMEOUT=60m

cd $SLURM_SUBMIT_DIR

module load ruby
module load pcp


# copy genes tarball to TMPDIR
cp $WORKDIR/genes.tar.gz $TMPDIR
time (cd $TMPDIR; tar xzf genes.tar.gz)

GENBANK_ROOT=$TMPDIR/genes ALIGNMENTS_CACHE_PATH=$WORKDIR/genes.db bin/rake pipeline:alignpcp


# tar up genes with alignments and copy back
time (cd $TMPDIR; tar czf genes_with_alignments.tar.gz genes)
cp $TMPDIR/genes_with_alignments.tar.gz $WORKDIR/genes.tar.gz
