#!/bin/bash
#PBS -l nodes=1:ppn=28
#PBS -l walltime=10:00:00
#PBS -N phylogatr_alignments
#PBS -j oe
#PBS -A PAS1604

set -xe

cd $PBS_O_WORKDIR

module load ruby
module load pcp
GENBANK_ROOT=/fs/project/PAS1604/pipeline/dev/genes ALIGNMENTS_CACHE_PATH=/fs/project/PAS1604/pipeline/dev/genes.db bin/rake pipeline:alignpcp

# TODO: will need to rsync back if we do this
# cp /fs/project/PAS1604/pipeline/dev/genes.db $TMPDIR
# cp -r /fs/project/PAS1604/pipeline/dev/genes $TMPDIR/genes
#
# module load ruby
#
# GENBANK_ROOT=$TMPDIR/genes ALIGNMENTS_CACHE_PATH=$TMPDIR/genes.db bin/rake pipeline:align
#
# TODO: rsync back $TMPDIR/genes to /fs/project/PAS1604/pipeline/dev/genes
