#!/bin/bash
#PBS -l nodes=1:ppn=4
#PBS -l walltime=20:00:00
#PBS -N phylogatr_alignments
#PBS -j oe
#PBS -A PAS1604

set -xe

cd $PBS_O_WORKDIR

module load pcp
module load ruby

# FIXME: change to find
# fd --type f --extension .fa --absolute-path --full-path . 'scratch/genbank/genes' | xargs -I {} echo ./align_sequences.sh {} > alignall
#
#
# ./align_sequences.sh /fs/scratch/PAS1604/genbank/genes/Actinopterygii/Acipenseriformes/Acipenseridae/Acipenser-ruthenus/Acipenser-ruthenus-COI.fa
# ./align_sequences.sh /fs/scratch/PAS1604/genbank/genes/Actinopterygii/Albuliformes/Albulidae/Albula-vulpes/Albula-vulpes-COI.fa

mpiexec parallel-command-processor alignall
