#!/bin/bash
#SBATCH --tasks=1
#SBATCH -t 4:00:00
#SBATCH --job-name="filter_bold"


BOLD_DIR=/fs/project/PAS1604/bold

cp $BOLD_DIR/* $TMPDIR
cd $TMPDIR

# 1   processid
# 3   recordID
# 4   catalognum
# 5   fieldnum
# 10  phylum_name
# 12  class_name
# 14  order_name
# 16  family_name
# 18  subfamily_name
# 20  genus_name
# 22  species_name
# 24  subspecies_name
# 47  lat
# 48  lon
# 70  markercode
# 71  genbank_accession
# 72  nucleotides

pids=()
for i in *tsv; do
  awk -F$'\t' 'BEGIN {OFS = FS} { if (NF==80 && $47 != "" && $48 != "" && $72 != "" && $22 != "") print $1, $3, $4, $5, $10, $12, $14, $16, $18, $20, $22, $24, $47, $48, $70, $71, $72 }' $i > filtered.$i &
  pids+=($!)
done
wait "${pids[@]}"

cat filtered.* > $BOLD_DIR.tsv
