name: Publish Docker image

on:
  push:
    tags:
      - '*'
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  push_to_registry:
    name: Push Docker image to OSC Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup the environment
        id: setup
        run: |
          TAG=${GITHUB_REF#refs/*/}
          REPO="docker-registry.osc.edu/gateways"
          LATEST_IMG="$REPO/phylogatr:latest"
          VERSIONED_IMG="$REPO/phylogatr:$TAG"
          echo "::set-output name=latest::$LATEST_IMG"
          echo "::set-output name=versioned::$VERSIONED_IMG"
      - name: docker build and tag
        run: |
          docker build -t ${{ steps.setup.outputs.latest }} .
          if [[ -n "${{ steps.setup.outputs.versioned }}" ]]; then
            docker tag ${{ steps.setup.outputs.latest }} ${{ steps.setup.outputs.versioned }}
          fi
      - name: login to osc harbor
        run: docker login -u ${{ secrets.OSC_DOCKER_REGISTRY_USER }} -p ${{ secrets.OSC_DOCKER_REGISTRY_TOKEN }}
      - name: push images to osc harbor
        if: ${{ github.push == 'create' && github.event.ref_type == 'tag' }}
        run: |
          docker push ${{ steps.setup.outputs.latest }}
          docker push ${{ steps.setup.outputs.versioned }}
